Page pg
REZAL-AM-KIN/kfet pull request #13
Opened 2022-10-23 16:34 UTC by Teiwin

oupsi doupsi

2022-10-25 20:20 UTC, Teiwin commented
problem with user context on login page

2022-10-28 12:17 UTC, OSiG43 reviewed
![image](https://user-images.githubusercontent.com/25371937/198584328-3c0cb6fa-37af-4bb6-a059-29d2ba5627be.png)
![image](https://user-images.githubusercontent.com/25371937/198584383-336530ff-1ef5-492a-b335-c99cf2314396.png)
Y'a un problème sur le haut de page

2022-10-28 12:28 UTC, OSiG43 requested changes
Pb d'espace qui change sur la navbar..

2022-10-28 12:49 UTC, OSiG43 approved these changes

2022-10-28 12:51 UTC, merged