Page pg
REZAL-AM-KIN/kfet pull request #14
Opened 2022-10-28 19:52 UTC by Teiwin

Catégories!!!!!!
lovely

(si tu trouve pas les boutons jolis, essaye de faire mieux :laughing: )

2022-11-04 09:44 UTC, OSiG43 requested changes

2022-11-04 09:44 UTC, OSiG43 commented on src/App.jsx
> +                    <CategorieProvider>
t'es sûr que tu veux pas le mettre avec User ? car pour moi c'est vraiment une info qui irait bien avec les infos de l'utilisateur : l'utilisateur a sélectionné la catégorie bidule

2022-11-04 09:44 UTC, OSiG43 commented on src/components/Categories.js
> +    }, [])
On a dit qu'on séparer la logique des composants du coup il faudrait que tout ça soit dans un hook custom. (y'en a plein dans la branche event si tu veux voir)

2022-11-04 09:44 UTC, OSiG43 commented on src/components/Categories.js
> +                    >{cat.name}</Button>
Pourquoi des bouttons plutôt qu'un Autocomplete ou un Native selecte ?

2022-11-04 09:44 UTC, OSiG43 commented on src/components/NavigationLinks.js
> +            withArrow
Je pense que c'est plus joli sans la flèche pour être cohérent avec recherche PG

2022-11-04 09:44 UTC, OSiG43 commented on src/components/Produits.js
> +                errorNotif("Debucquage", error);
Dans un Hook custom du coup

2022-11-04 09:44 UTC, OSiG43 commented on src/pages/PG.jsx
>              controller.abort();
Hook custom

2023-01-28 17:26 UTC, Teiwin commented on src/App.jsx
> +                    <CategorieProvider>
Ma pensée était la suivante:
Toutes les infos qu'on met en context comme à ce niveau ci sont vouées à être utiliséees partout dans le site.
On pourrait donc créer un seul context et mettre dedans Mantine theme, l'utilisateur, la catégorie sélectionnée, etc...

Mais ça ferait un context énorme et difficile à exploiter.
En découpant comme ça on garde des contextes plus petits, plus facile à comprendre et à utiliser. (lorsque on l'utilise on ne se retrouve pas avec une liste de n éléments dont on en utilise 1 seul)

Je pense que ce sont deux informations qui ne sont pas utilisées en même temps et qui ne devraient donc pas avoir le même context.

(remember: i can be wrong)

2023-01-28 17:28 UTC, Teiwin commented on src/components/Categories.js
> +                    >{cat.name}</Button>
je trouvais ça plus visuel et plus simple d'utilisation sur écrant tactile.
on peut tout de même faire un autocomplete pour grands écrans. J'ai peur du rendu cependant.

2023-12-29 00:05 UTC, closed without merging