Event
REZAL-AM-KIN/kfet pull request #15
Opened 2023-01-27 14:11 UTC by OSiG43

Cette PR regroupe l'ensemble des fonctionnalités pour la gestion des événements. 
Rendez-vous dans la page fin'ss pour voir les ajouts de cette PR.

UAI: Il manque encore l'implémentation des permissions pour : la création d'un finss, le débucquage, le débucquage en negat'ss

2023-03-11 20:33 UTC, Teiwin requested changes
Plus jamais ça... 6h pour review ta pr de 3k lignes...

2023-03-11 20:33 UTC, Teiwin commented on src/pages/FinssEditPages/FinssParameters.js
> +            <Tabs.List grow position="apart">
Alors, les tabs, oui, mais non (enfin pas comme ça :smile: )
![image](https://user-images.githubusercontent.com/107307293/224509197-81f054bf-056e-4ca2-b468-a500637f0caf.png)

et en format mobile:
![image](https://user-images.githubusercontent.com/107307293/224509225-39ca218c-04c9-4d35-adea-cfced054e925.png)

faut trouver une solution. :rofl: 

Peut-être mettre les 2 papers à coté si l'écran est assez large? (à voir avec la modif du paper des produits)

2023-03-11 20:33 UTC, Teiwin commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                    selectedRecords = {selectedRecords}
Les pg sélectionnés puis débucqués restent sélectionnés.
![Screenshot from 2023-03-11 20-54-40](https://user-images.githubusercontent.com/107307293/224509435-bc582452-6391-46ac-bb7b-d4b4458a840b.png)

2023-03-11 20:33 UTC, Teiwin commented on src/components/Finss/FinssGeneralParameters.js
> +                            Tous les débucquages non pas été effectués.<br/>
```suggestion
                            Tous les débucquages n'ont pas été effectués.<br/>
```

2023-03-11 20:33 UTC, Teiwin commented on src/components/Finss/FinssGeneralParameters.js
> +                        <Button fullWidth color="red" onClick={closeAllModals} mt="md">C'est compris.</Button>
je chipote: déplacer le bouton {C'est compris} à un autre endroit que le bouton {Cloturer le fin's} de la dernière modale?
histoire d'obliger l'utilisateur à bouger la souris pour confirmer la cloture (et eviter les double clics beaucoup trop rapidement instinctifs)

2023-03-11 20:33 UTC, Teiwin commented on src/components/Finss/FinssProductsParameters.js
> +                        Les inscriptions liées à ce produit seront <i><u><b>définitivement</b></u></i> supprimer.
```suggestion
                        Les inscriptions liées à ce produit seront <i><u><b>définitivement</b></u></i> supprimées.
```

2023-03-11 20:33 UTC, Teiwin commented on src/components/Finss/FinssProductsParameters.js
> +                <Tabs keepMounted={false} orientation="vertical" defaultValue={usefinssproduct.productsList.length>0 ? usefinssproduct.productsList[0].id.toString() : ""}>
C'est rigolo avec les long nom en format mobile:
![image](https://user-images.githubusercontent.com/107307293/224509943-95e403a1-7bc8-49c4-bcdd-cfb0219b922e.png)

(ça marche pas bien, et la limite de 30 char ne résouds pas le pb. le Gaspacho est à 25 char et des poussières)
mais j'aime bcp la présentation.
Mettre un wrap?

2023-03-11 20:33 UTC, Teiwin commented on src/components/ManagersSelector.jsx
> +      <MultiSelect
Le select qui est affiché est le nom de famille. Qui ne permet pas une identification unique d'un PG

(bucque fam's)?

2023-03-21 00:49 UTC, OSiG43 commented on src/components/Finss/FinssRegisterModal.js
> +            }
Corrigé dans le commit [7ae2265](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/7ae226549307ef24188d7e6c4e408414a2e0ff26)

2023-03-21 00:50 UTC, OSiG43 commented on src/hooks/finssHooks/useUserParticipation.js
> +                errorNotif("Finss", "Une erreur inconue est survenue lors de l'envoi des participations")
Corrigé : cf [213a7ee](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/213a7eef4fb495d6b0d66e20ebf459900a5ab2bb)

2023-03-21 01:10 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssBucquage.js
> +    }
cf [75e2939](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/75e29394010507119966f4a79f779e8eb3960ad3)

2023-03-21 01:10 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssBucquage.js
> +                                    </>
cf :[75e2939](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/75e29394010507119966f4a79f779e8eb3960ad3)

2023-03-21 01:16 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssBucquage.js
> +                                <th>Pré Qts</th>
Je sais pas trop quoi faire pour ça...
en vrai je me dis que ce sera vite accepté nan ?
genre si tu l'utilise une fois tu comprends nan ?

2023-03-21 02:16 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssBucquage.js
> +                          {accessor: "consommateur_prenom", title:"Prénom", sortable: true},
cf : [e51f995](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/e51f9956aa7b4266c8b6ecb370f0929a2d5990e8)

2023-03-21 02:16 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssPrebucquage.js
> +                                {accessor: "consommateur_prenom", title:"Prénom", sortable: true},
cf: [e51f995](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/e51f9956aa7b4266c8b6ecb370f0929a2d5990e8)

2023-03-21 02:16 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssPrebucquage.js
> +                <SearchableDataTable
cf :[e51f995](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/e51f9956aa7b4266c8b6ecb370f0929a2d5990e8)

2023-03-21 02:16 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssBucquage.js
> +                    <Table withBorder withColumnBorders style={{tableLayout:"fixed", wordBreak:"break-word"}}>
cf :[e51f995](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/e51f9956aa7b4266c8b6ecb370f0929a2d5990e8)

2023-03-21 02:17 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                <SearchableDataTable
cf :[e51f995](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/e51f9956aa7b4266c8b6ecb370f0929a2d5990e8)
normalement aucun pb sur la recherche

2023-03-21 02:19 UTC, OSiG43 commented on src/components/Finss/FinssProductRecapModal.js
> +                        {accessor: "quantite_bucque", title:"Qts"},
j'ai pas ce bug, plus de détails ?

2023-03-21 02:28 UTC, OSiG43 commented on src/components/ManagersSelector.jsx
> +      <MultiSelect
cf :[350f1e6](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/350f1e6939bd27453058dd47fd019547c6c62fd8)

2023-03-21 02:29 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                        }
Pas réussi à reproduire, plus de détails ?

2023-03-22 12:09 UTC, Teiwin commented on src/pages/FinssEditPages/FinssBucquage.js
> +                                <th>Pré Qts</th>
J'aime bien le qté/Bucqué, moins de ligne et on voir le rapport pris/bucqué

2023-11-11 21:30 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssBucquage.js
> +                                <th>Pré Qts</th>
![image](https://github.com/REZAL-AM-KIN/kfet/assets/25371937/fc1da2a3-305e-4a23-84fe-fec440147d58)

2023-11-11 21:59 UTC, OSiG43 commented on src/components/Finss/FinssGeneralParameters.js
> +                        <Button fullWidth color="red" onClick={closeAllModals} mt="md">C'est compris.</Button>
J'ai essayé de faire un délai avant de pouvoir cliquer dessus mais c'est trop complexe (modal via modalManager non reactive...)

Donc tant pis, ya quand même 2 modal de confirmation, après faut pas que le gars soit trop con !

2023-11-12 00:22 UTC, OSiG43 commented on src/components/Finss/FinssProductsParameters.js
> +                <Tabs keepMounted={false} orientation="vertical" defaultValue={usefinssproduct.productsList.length>0 ? usefinssproduct.productsList[0].id.toString() : ""}>
Corrigé !
Sur mobile 
![image](https://github.com/REZAL-AM-KIN/kfet/assets/25371937/28eba0c5-e75f-4c11-8f10-1f482cccb702)

Sur PC:
![image](https://github.com/REZAL-AM-KIN/kfet/assets/25371937/7919a044-4264-4eac-bad0-7857b8a41b8f)

La taille max pour la liste est désormais 35% de la fenetre parametres

2023-11-12 01:28 UTC, OSiG43 commented on src/components/Finss/FinssProductRecapModal.js
> +                        {accessor: "quantite_bucque", title:"Qts"},
Réglé !
Cf commit: 32827abb95204407929fa2c0f9d03e5a428c7471

2023-11-12 01:51 UTC, OSiG43 commented on src/components/Finss/FinssBucquageModal.js
> +                    <Button style={{flex:"auto", marginTop: 10, marginLeft: "3px", backgroundColor: theme.colors.green[6]}} type="submit" name="Continue" disabled={!selectedPG}>Bucquage suivant</Butt
Fix mais pas trop...
Le map de l'action enter est pas sublime. De toute façon, malheuresement la partie fin'ss est pas vachement pensé pour une utilisation full clavier.
C'est toujours mieux que le site actuelle, ça pourra faire parti d'une amelioration future.

2023-11-12 01:52 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                        }
toujours pas compris le bug.

2023-11-23 15:24 UTC, Teiwin commented on src/pages/FinssEditPages/FinssBucquage.js
> +    }
la barre est toujours aussi petite
![Screenshot_20231123_162437](https://github.com/REZAL-AM-KIN/kfet/assets/107307293/e621bdd5-e266-479b-9919-65e12d665f36)

2023-11-23 15:32 UTC, Teiwin submitted a review, later dismissed
wow, c'est quoi ça ?
![Screenshot_20231123_163045](https://github.com/REZAL-AM-KIN/kfet/assets/107307293/61ac05ac-adac-4bb9-bbeb-36d3f4802bc9)

dès qu'on ouvre la modale de récap des produits et des bucquages, elle se refresh en boucle et fait un nomvre de requête ahurissant. (350 requêtes en 5 secondes) 😆 

Je me disais aussi que mon pc turbinait bcp pour une simple modale.
j'ai pas trouvé d'où ça viens

2023-11-23 15:35 UTC, Teiwin commented
> wow, c'est quoi ça ? ![Screenshot_20231123_163045](https://user-images.githubusercontent.com/107307293/285252746-61ac05ac-adac-4bb9-bbeb-36d3f4802bc9.png)
> 
> dès qu'on ouvre la modale de récap des produits et des bucquages, elle se refresh en boucle et fait un nomvre de requête ahurissant. (350 requêtes en 5 secondes) 😆
> 
> Je me disais aussi que mon pc turbinait bcp pour une simple modale. j'ai pas trouvé d'où ça viens

note, ça fait aussi ça dans la modale débucquage/récap des prix

2024-06-30 14:47 UTC, peufgeul commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                        }
le bug intervient quand record.prix_total n'existe pas, ce qui est le cas tant qu'on ne clique pas sur le bouton recap prix

2024-06-30 19:49 UTC, peufgeul commented on src/pages/FinssEditPages/FinssBucquage.js
> +    }
cf [84b97b7](https://github.com/REZAL-AM-KIN/kfet/pull/15/commits/84b97b7b35bdc60398eb6897ec050862c25d4b20)

2024-06-30 20:15 UTC, peufgeul reviewed
petit soucis avec la page de débucquage quand le prix des produits n'est pas encore calculé.

aussi, j'ai l'impression qu'il y a des appels à l'api bizarre.
quand on va sur l'onglet Bucquage, il y a un appel de http://172.20.10.2:8000/api/bucquagevent/my_bucquages/
et quand on va sur l'onglet Debucquage il y a un appel de http://172.20.10.2:8000/api/consommateurs/

aussi, il n'y a pas de fenêtre de confirmation/d'erreur des requêtes en bas à droite qui s'affiche, alors que je crois qu'elles sont définit dans les hooks. est-ce que le problème vient de ma config? j'ai essayé avec firefox et chromium.

et je suis un singe, j'ai oublié de mettre request change

2024-06-30 20:15 UTC, peufgeul commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                        <Text>{record.prix_total}€</Text>
on a ici le Nan affiché si le prix de chaque produit n'a pas été calculé (et donc que le prix total ne peut être calculé)
![pb quand pas de calcul des prix](https://github.com/REZAL-AM-KIN/kfet/assets/98660368/f0425f57-71e4-4b86-9990-3239ead3ffb8)

2024-06-30 20:15 UTC, peufgeul commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                        </List>
taille de police différente du reste
![pb quand pas de calcul des prix](https://github.com/REZAL-AM-KIN/kfet/assets/98660368/b0a6071a-72ed-4226-b4a0-edc9668969bf)

2024-08-19 15:48 UTC, peufgeul commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                        <Text>{record.prix_total}€</Text>
visiblement c'est fix avec REZAL-AM-KIN/niki-s#56

2024-08-19 20:31 UTC, peufgeul requested changes
encore quelques éléments à implémenter (ou au moins discuter de leur implémentation)

2024-08-19 20:31 UTC, peufgeul commented on src/components/Finss/FinssBucquageModal.js
> +                   </Group>
est-ce qu'on ajout une zone de texte avec le solde du pg, et le solde requis vis-à-vis des produits pour lesquels il est entrain de se faire bucquer?
ça nous obligerais à calculer le solde requis aux changement des QtsInput, et rendrait plus clair pourquoi le solde est insuffisant

2024-08-19 20:31 UTC, peufgeul commented on src/components/Finss/FinssBucquageModal.js
> +                           ]}
est-ce qu'on rajoute une colonne pour indiquer le solde requis pour chaque produit? (solde requis pour 1 * la valeur du champ QtsInput)

2024-08-19 20:31 UTC, peufgeul commented on src/pages/FinssEdit.js
> +                </Tabs.List>
est-ce qu'il faudrait pas adapter les tab visible/activé en fonction de l'état du fin'ss?

2024-08-19 20:31 UTC, peufgeul commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                    }}
A modifié pour permettre aux utilisateurs qui peuvent débucquer des fin'ss en négat'ss de sélectionner ces lignes

2024-08-21 13:22 UTC, OSiG43 commented
![image](https://github.com/user-attachments/assets/0f1bfc7c-7386-4883-9119-6d0f9969ac3b)
Faute d'ortho: "une fin'sss" au lieu de "un fin'ss"

2024-08-21 13:25 UTC, OSiG43 commented
![image](https://github.com/user-attachments/assets/efc4ea15-4b42-4980-9b23-1472c5810054)
Prix min ne s'affiche plus dans le recap produit sur la page de bucquage d'un finss

2024-08-21 13:27 UTC, OSiG43 commented
![image](https://github.com/user-attachments/assets/a4a2ce28-cc5d-4c27-b835-91bd7b377446)
Il faudrait peut-être permettre la modification des prix des produits lorsque d'état du fin'ss est "débucquage"

2024-08-21 13:34 UTC, OSiG43 commented on src/components/Finss/FinssBucquageModal.js
> +                   </Group>
Ce serait génial en effet

2024-08-21 13:35 UTC, OSiG43 commented on src/components/Finss/FinssBucquageModal.js
> +                           ]}
hmm je dirais que ça vaut le coup si tu implementes la fonctionnalité qui fait un recap du solde PG comme expliqué dans le commentaire précédent

2024-08-21 13:36 UTC, OSiG43 commented on src/pages/FinssEdit.js
> +                </Tabs.List>
je trouve que c'est mieux de les avoir en disable, comme ça l'utilisateur comprends qu'il est bien au bonne endroit mais que c'est désactivé

2024-08-21 13:37 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                    }}
J'allais le dire !
mais il manque une gestion des permissions non, genre ya pas d'endpoint pour check les accès pour le moment si ?

2024-08-21 14:53 UTC, OSiG43 commented on src/pages/FinssEditPages/FinssDebucquage.js
> +                    }}
j'ai rien dit. du coup oui il faut le faire.

2024-08-22 07:06 UTC, peufgeul commented
> ![image](https://private-user-images.githubusercontent.com/25371937/359914824-a4a2ce28-cc5d-4c27-b835-91bd7b377446.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTA0MDcsIm5iZiI6MTcyNDMxMDEwNywicGF0aCI6Ii8yNTM3MTkzNy8zNTk5MTQ4MjQtYTRhMmNlMjgtY2M1ZC00YzI3LWI4MzUtOTFiZDdiMzc3NDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTg2N2Y1OWNlN2ZjMjVhNmE0NzQxN2FmYTUwZjk0OWJlNjJmNGY2YTlmNjg0NDg5OTM0NGViYWU2MGU1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PewnBo1U8f-j_dAbP_0B9lkPyf9wZK4tnKiSonah8Bc) Il faudrait peut-être permettre la modification des prix des produits lorsque d'état du fin'ss est "débucquage"

ça je suis pas fan. Ou alors il faut vérifier si quand le fin'ss est dans l'état débucquage, on n'a débucqué aucune fois ce produit (et aussi l'implémenter côté backend). Parce que sinon, si tu as commencé à débucquer et que tu modifies le prix total après, tout les participant n'auront pas été débucqué avec le même prix à l'unité

2024-08-22 14:19 UTC, peufgeul approved these changes

2024-08-23 14:26 UTC, peufgeul approved these changes
das good shit

2024-08-24 13:49 UTC, merged