Categories
REZAL-AM-KIN/kfet pull request #16
Opened 2023-02-15 19:44 UTC by Teiwin

Branche concernant que les catégories.

Please review.

les hooks custom seront l'objet d'une autre pr?

 il faut trouver des couleurs bonnes et un meilleur style

2023-09-03 07:34 UTC, peufgeul commented
ajout d'un hooks poru l'endpoint /entities/ et correction des noms des attributs

2023-09-03 07:48 UTC, Teiwin commented
> ajout d'un hooks pour l'endpoint /entities/ et correction des noms des attributs
> 
> Pour le moment le context catégorie est initié à une valeur qui n'a rien à voir avec les catégories (ipidentification ou gorupe de l'utilisateur).
> Est-ce qu'on prévoit de se souvenir de la catégorie sélectionnée par l'utilisateur sur un session précédente, ou on initialise à aucune catégorie?

se souvenir c'est compliqué. l'utilisateur à accès à certaines catégories seulement. peut être qu'on peut se baser là dessus et mettre des priorités: le PG à accès à kfet et cvis pour débuquer, il se connecte à partir du pian's cvis. bon, on va lui mettre cvis.

2023-11-09 14:04 UTC, Teiwin commented
J'ai changé le nom de l'élément requireAuth puisqu'il ne vérifie pas seulement si l'utilisateur est connecté, mais se charge aussi de fournir la navbar et le contexte de catégorie

2023-11-11 19:53 UTC, OSiG43 reviewed
# Commentaires UI/UX : 
## Commentaires générals
![image](https://github.com/REZAL-AM-KIN/kfet/assets/25371937/34e9282a-80b8-4c16-a41a-644d651ac21e)
Dommage que la catégorie sélectionnée ne soit visuellement indiqué dans le sélecteur (contour de selection, couleur différente, ect...) 

Pb de layout : 
La taille de bouton est en fit-content du coup, il n'y a pas d'uniformisation de la taille des boutons ce qui provoque un désalignement des boutons suivant la longueur des noms.
De plus, cela cause une importante marge à droite entre les boutons et la fin de la popover pour les lignes à catégories avec des petits noms.

J'aime beaucoup le nom de la catégorie affiché en dessous du bouton !

## Bugs
![image](https://github.com/REZAL-AM-KIN/kfet/assets/25371937/caf9c4ec-d815-4342-a5c7-b727b9754dd3)
Lorsqu'une catégorie est sélectionnée, le bouton du categorieSelector devient noir et le reste.

2023-11-11 19:57 UTC, OSiG43 commented
> > ajout d'un hooks pour l'endpoint /entities/ et correction des noms des attributs
> > Pour le moment le context catégorie est initié à une valeur qui n'a rien à voir avec les catégories (ipidentification ou gorupe de l'utilisateur).
> > Est-ce qu'on prévoit de se souvenir de la catégorie sélectionnée par l'utilisateur sur un session précédente, ou on initialise à aucune catégorie?
> 
> se souvenir c'est compliqué. l'utilisateur à accès à certaines catégories seulement. peut être qu'on peut se baser là dessus et mettre des priorités: le PG à accès à kfet et cvis pour débuquer, il se connecte à partir du pian's cvis. bon, on va lui mettre cvis.

Perso je suis plutôt pour au moment le mettre dans le localStorage.

2023-11-11 21:07 UTC, OSiG43 requested changes

2023-11-11 21:07 UTC, OSiG43 commented on src/hooks/useCategorieCtxt.jsx
Manque un docstring pour indiquer le fonctionnement (forme des objets renvoyés, ect..)

2023-11-11 21:07 UTC, OSiG43 commented on src/context/Categorie.jsx
> +            if (permissions.entities_manageable.length) {
Lors de ma review, le champ entities_manageable n'étais pas renvoyé par le back (branche main).
La modification n'est pas obligatoire mais ne mange pas de pain : 
```suggestion
            if (permissions.entities_manageable?.length) {
```
Pour être certain de pouvoir lire length ou d'avoir un undefined propre (sans crash) si entities_manageable n'existe pas dans l'objet.

2023-11-11 21:07 UTC, OSiG43 commented on src/context/Categorie.jsx
> +            } else if (permissions.entities.length) {
```suggestion
            } else if (permissions.entities?.length) {
```

Pareil, ça ne mange pas de pain.

2023-11-12 10:26 UTC, Teiwin commented on src/components/NavigationBar.jsx
> +                            </Center>
le format mobile est globalement nul.
en vrai faudrait faire.un autre layout totalement pour le faire bien.

la on essaye de combiner format kfet (petit écran), format pc grand écran et tel.
le kfet et grand écran, on peut le faire sur le même code.
le format tel est trop différent et faut faire plus que retirer les padings etc...

2023-11-24 16:13 UTC, Teiwin commented on src/components/Authentified.jsx
> +        </CategorieProvider>
je comprends pas bien ce que tu veux dire.

2023-11-24 16:21 UTC, Teiwin commented on src/App.jsx
>                                  </Route>
faire un truc comme ça mais avec `<><NavigationBar width={navBarWidth} page={page}/><Outlet/></>` dans un element?
en vrai, je me dit, le mettre dans l'export de la  NavBar?

```js
<Route element={<Autentified/>}>
    <Route element={<><NavigationBar width={navBarWidth} page={page}/><Outlet/></>}>
        <Route path="/" element={<Home setPage={setPage}/>}/>
        <Route path="pg/:pgId" element={<PG setPage={setPage}/>}/>
        <Route path="edit" element={<Edit setPage={setPage}/>}/>
        <Route path="finss" element={<Finss setPage={setPage}/>}/>
    </Route>
</Route>
```

2023-11-24 16:26 UTC, Teiwin commented on src/components/Authentified.jsx
> +        </CategorieProvider>
et une solution comme ça?
avec `<><NavigationBar width={navBarWidth} page={page}/><Outlet/></>` dans l'export de la NavigationBar
aussi, la manière dont on utilise React router n'est pas la plus récente, ni la meilleure. à voir dans une prochaine branch.
```js
<Route element={<Autentified/>}>
    <Route element={<><NavigationBar width={navBarWidth} page={page}/><Outlet/></>}>
        <Route path="/" element={<Home setPage={setPage}/>}/>
        <Route path="pg/:pgId" element={<PG setPage={setPage}/>}/>
        <Route path="edit" element={<Edit setPage={setPage}/>}/>
        <Route path="finss" element={<Finss setPage={setPage}/>}/>
    </Route>
</Route>
```

2023-11-24 16:42 UTC, Teiwin commented on src/components/NavigationBar.jsx
> +                            </Center>
effectivement.
je pense qu'on devrais afficher en permanence en haut la recherche de PG. ça permettrait une interraction plus fluilde et aussi résoudrait l'issue #11  en permettant de mettre le burger menu à gauche, suivi de la bare de recherche.

Effectivement, la catégorie rends moche 
![Screenshot_20231124_174012](https://github.com/REZAL-AM-KIN/kfet/assets/107307293/15cd4fec-c86e-48cc-962f-b581d959dd33)

2023-11-24 16:59 UTC, Teiwin commented on src/components/NavigationBar.jsx
> +                </Navbar.Section>
![image](https://github.com/REZAL-AM-KIN/kfet/assets/107307293/3a70e810-90f8-4a95-9b05-d5e1b68dc732)

2023-11-24 17:00 UTC, Teiwin commented on src/components/RechargeButton.jsx
le bouton était vert, pas de danger !
 en vrai, faut bien le faire à un moment .

2023-11-24 17:01 UTC, Teiwin commented on src/components/NavigationLinks.jsx
créé issue pour ça. jsp si c'est le bon mouv, mais bon... je sais pas comment faire de todo

2023-11-28 15:06 UTC, Teiwin commented on src/components/Authentified.jsx
> +        </CategorieProvider>
bon, j'ai fait un truc.

2023-11-28 15:07 UTC, Teiwin commented on src/components/NavigationBar.jsx
> +                </Navbar.Section>
solution du millieu

2023-11-29 22:34 UTC, Teiwin commented on src/components/Authentified.jsx
> +        </CategorieProvider>
sollution pas mal trouvée 
ainsi que clean de la navbar et de la gestion de son affichage

2023-12-12 16:28 UTC, Teiwin commented on src/components/CategoriesSelector.jsx
> +}
ombrage pour donner du relief et faire pop out les boutons

2023-12-18 12:32 UTC, Teiwin reviewed
lgtm

2023-12-18 12:47 UTC, merged