NavBar UI update
REZAL-AM-KIN/kfet pull request #29
Opened 2024-05-27 14:37 UTC by peufgeul

Fix des quelques souci autour de la NavBar:

Réorganisation des composants de la NavBar dans plusieurs fichiers, dans un dossier NavLinks
Ajout d'un fichier NavbarButtonStyle.jsx pour avoir le style des boutons de la NavBar au même endroit

Ajout d'un bouton pour aller à l'accueil (et suppression du bouton "debuquage" vu qu'il ne sert à rien)

Et correction de l’absence de changement de style du bouton de la NavBar correspondant à la page actuelle
![Capture d’écran du 2024-05-27 16-37-36](https://github.com/REZAL-AM-KIN/kfet/assets/98660368/1a7491f8-ae32-48c7-821f-506794e1376d)

2024-05-27 14:54 UTC, Teiwin commented
on l'attendait 🤩

une correction du format mobile aussi?

2024-05-27 18:47 UTC, peufgeul commented
> on l'attendait 🤩
> 
> une correction du format mobile aussi?

Nan, pas dans celle-là.
Je ferais dans une autre branche pour le tel

2024-08-21 15:42 UTC, OSiG43 requested changes

2024-08-21 15:42 UTC, OSiG43 commented on src/components/NavLinks/NavbarButtonStyle.jsx
> +export const useStyles = createStyles((theme) => ({
rename to something like useNavabarButtonStyle

2024-08-21 15:42 UTC, OSiG43 commented on src/components/NavLinks/NavbarButtonStyle.jsx
add padding to avoid this:
![image](https://github.com/user-attachments/assets/aab5d130-a24e-44c3-884d-c5eba2830ec9)

2024-08-22 12:38 UTC, peufgeul commented on src/components/NavLinks/NavbarButtonStyle.jsx
si c'est bien pour que les boutons ne se touchent pas, c'est du margin

2024-08-22 12:42 UTC, peufgeul commented on src/components/NavLinks/NavbarButtonStyle.jsx
![Capture d’écran du 2024-08-22 14-41-54](https://github.com/user-attachments/assets/a6b0a05d-d7ab-486e-835a-01680748e584)

2024-08-22 12:45 UTC, OSiG43 approved these changes

2024-08-22 12:46 UTC, merged