UI pour recherche pg sur PC terminé
REZAL-AM-KIN/kfet pull request #7
Opened 2022-10-02 22:40 UTC by OSiG43

Manque seulement la fermeture de la recherche lors de l'appui sur echape.

2022-10-03 16:48 UTC, Teiwin requested changes
C'est jolie, mais il faut qu'on puisse rechercher avec tous les champs.

2022-10-03 16:48 UTC, Teiwin commented on package.json
>      "@mantine/core": "^5.4.0",
Est-ce que la 5.5(.1) apporte quelque chose?

2022-10-03 16:48 UTC, Teiwin commented on src/components/SearchPg.jsx
> +        return {id: pg.id, value: pg.bucque, fams: pg.fams, nom: pg.nom, prenom: pg.prenom, proms: pg.proms}
Est-ce la bonne solution? La node `Autocomplete` a l'air de ne compléter que la `value`. Ici je n'arrive à recherche qu'avec la bucque.
Ce serait bien (voir plutôt, c'est obligé) de pouvoir rechercher par fam's, nom, prénom, prom's en plus de la bucque.

2022-10-03 16:50 UTC, Teiwin commented on package.json
>      "@mantine/core": "^5.4.0",
Certains components ont plus d'options, à voir? [mantine releases](https://github.com/mantinedev/mantine/releases)

2022-10-05 00:02 UTC, OSiG43 commented on src/components/SearchPg.jsx
> +        return {id: pg.id, value: pg.bucque, fams: pg.fams, nom: pg.nom, prenom: pg.prenom, proms: pg.proms}
J'ai commit pour résoudre le pb.
Je pourrais faire un filtre plus évolué qui prend en compte l'espace comme séparateur de critère genre "galand 221" recherche tous les galand de la 221 mais je sais pas si c'est vraiment utile

2022-10-05 14:56 UTC, Teiwin approved these changes
juste un pb de recherche, je vais créer une issue

2022-10-05 21:31 UTC, merged