Homepage
REZAL-AM-KIN/kfet pull request #8
Opened 2022-10-03 21:23 UTC by Teiwin

Homepage is near to be finished, 
PgCard was improved (still not responsive)
errorNotification was added
History was created

2022-10-04 23:09 UTC, OSiG43 reviewed
![image](https://user-images.githubusercontent.com/25371937/193946873-7600f265-aac6-4794-b2b7-b1d3c8f3698f.png)
Je ne comprends pas trop l'intéret des flèches sur l'historique

2022-10-04 23:10 UTC, OSiG43 commented
Je suis pas fan du set de couleur sur la PgCard, c'est pas très fin, ça fait vraiment dev qui a fort fort la flemme de faire de l'UI.
Je pense qu'il faudrait revoir ça
![image](https://user-images.githubusercontent.com/25371937/193947035-977667d8-40a3-486b-809a-ab6d4b6e9a88.png)
![image](https://user-images.githubusercontent.com/25371937/193947055-adaca15b-9203-4be9-9426-800051004b23.png)

2022-10-04 23:14 UTC, OSiG43 commented
J'ai vu que tu as utilisé des grids. Sauf erreur de ma part, les grids c'est très souvent très chiant pour faire du responsive.
Il vaut mieux utiliser les containers Groupe et Stack je crois

2022-10-04 23:23 UTC, OSiG43 commented
<img width="442" alt="image" src="https://user-images.githubusercontent.com/25371937/193948360-335379d4-d1a4-45e7-92df-5f7cb80939a0.png">
Overlap à régler

2022-10-04 23:24 UTC, OSiG43 commented
![image](https://user-images.githubusercontent.com/25371937/193948421-056163f7-7562-46e4-ae6f-8072417049ae.png)
La PGCard dans l'historique c'est vraiment une super idée !

Par contre ce serait cool que la fam'ss soit en justifié (genre de l'autre coté de la card) facile à faire avec Group en plus.

2022-10-04 23:27 UTC, OSiG43 commented
D'un points de vu structure de code, je pense que ça vaut vraiment le Coup d'avoir un élément PgHistory et un élément GénéralHistory, car passer en props "general" ça risque de devenir un peu fouilli j'ai peur. Surtout pour faire le responsive.

2022-10-04 23:37 UTC, OSiG43 requested changes
J'ai vraiment fait une review complète complète comme ça tout nos échanges sont sur github, ça centralise au moins.

Sinon hésites pas à vraiment commenter (sur commenter) à balle, il va falloir que la passa'ss/amélioration face plusieurs générations ;)

2022-10-04 23:37 UTC, OSiG43 commented on src/components/ErrorNotif.js
> +const errorNotif = (localisation, message) => {
Bonne idée mais où est le NotificationProvider ? il devrait être dans App

2022-10-04 23:37 UTC, OSiG43 commented on src/components/History.js
> +                {general
Remarque déjà fait en commentaire sur la séparation des components pour historique général et historique pg

2022-10-04 23:37 UTC, OSiG43 commented on src/pages/Home.js
> +  }, [axiosPrivate]);
Je suis curieux de comprendre pourquoi tu passes axiosPrivates en deps, je capte pas l'interêt

2022-10-04 23:37 UTC, OSiG43 commented on src/components/PgCard.jsx
> +export default function PgCard({data, small, onClick, style}) {
Même remarque que pour les historiques. Dans un seul component, tu créés 3 éléments avec des formes et des informations affichées différentes.
Selon moi ça doit être 3 components différents.

2022-10-05 10:49 UTC, Teiwin commented on src/components/ErrorNotif.js
> +const errorNotif = (localisation, message) => {
Ptdr ca marchera quand ton code aura été merge

2022-10-05 15:53 UTC, Teiwin commented on src/pages/Home.js
> +  }, [axiosPrivate]);
mb c'est un test qui est passé à la trape

2022-10-05 16:41 UTC, Teiwin commented on src/components/PgCard.jsx
> +export default function PgCard({data, small, onClick, style}) {
je vois mal comment séparer ces 3 éléments.
Ce sont juste des PgCards avec une taille différente / un message d'erreur si les data sont incomplètes.
On passe les mêmes arguments, pour moi ce n'est qu'un seul élément.

Donc?

2022-10-05 17:21 UTC, Teiwin commented on src/components/History.js
> +                {general
je ne vois pas ce que tu veux dire avec "ça risque de devenir un peu fouilli j'ai peur. Surtout pour faire le responsive."?

2022-10-05 18:42 UTC, Teiwin commented
> 

je n'ai pas d'idée de comment faire, les test que j'ai fait ne sont pas concluants... TODO?

2022-10-05 18:43 UTC, Teiwin commented
> ![image](https://user-images.githubusercontent.com/25371937/193948421-056163f7-7562-46e4-ae6f-8072417049ae.png) La PGCard dans l'historique c'est vraiment une super idée !
> 
> Par contre ce serait cool que la fam'ss soit en justifié (genre de l'autre coté de la card) facile à faire avec Group en plus.

je n'ai pas d'idée de comment faire, les test que j'ai fait ne sont pas concluants... TODO?

2022-10-05 18:44 UTC, Teiwin commented
j'ai modifié l'historique pour que ce soit plus intuitif pour l'utilisateur... à voir ce que ça donne

2022-10-05 21:33 UTC, OSiG43 commented on src/components/PgCard.jsx
> +export default function PgCard({data, small, onClick, style}) {
Entre la small et la normal, ya quand même une grosse grosses différence d'ui. Visuellement ce sont 2 composants bien différents. C'est pas juste la taille qui change.

2022-10-05 21:36 UTC, OSiG43 commented on src/components/History.js
> +                {general
en gros pour faire du responsive, surtout avec les mediaqueries, tu vas devoir mettre des conditions dans ton code (dans le return) et duc'ss ça risque de faire des empilements de conditions pas très jolie.
Ce sera plus simple déjà si tu as deux composants distinct (après c'est mon avis, j'ai pas vraiment les bonnes pratiques mais d'après les exemples d'internet c'est plutôt comme ça).
En plus ce ne sont pas les mêmes composants (pas le même contenu)

2022-10-05 21:55 UTC, OSiG43 commented
> > ![image](https://user-images.githubusercontent.com/25371937/193948421-056163f7-7562-46e4-ae6f-8072417049ae.png) La PGCard dans l'historique c'est vraiment une super idée !
> > Par contre ce serait cool que la fam'ss soit en justifié (genre de l'autre coté de la card) facile à faire avec Group en plus.
> 
> je n'ai pas d'idée de comment faire, les test que j'ai fait ne sont pas concluants... TODO?

![image](https://user-images.githubusercontent.com/25371937/194171089-4c05934f-2fd3-40ad-8d8f-08ede455887a.png)
Done
![image](https://user-images.githubusercontent.com/25371937/194171127-15bf6751-7565-45f2-9294-e1d7ac993a23.png)

Utilise vraiment un max les mises en page avec les styles (bon la avec les components et props comme on utilise mantine) c'est plutôt comme ça qu'il faut faire en web ( en plus comme ça le composant devient comme par magie quasi responsive)

2022-10-05 22:00 UTC, OSiG43 commented
> j'ai modifié l'historique pour que ce soit plus intuitif pour l'utilisateur... à voir ce que ça donne
> 
> tabs à supprimer sur mobile

C'est pas mal !
Seul point à améliorer (jsp si c'est faisable sans trop de pb) : c'est bizzare que le carousel tourne dans un sens qui n'est pas forcement celui du passage d'une tab à l'autre. 
au lieu d'avoir une rotation complète, ce serait bien que, quand on est sur Perso, la flèche droite soit bloquée et quand on est sur général, la fléche gauche soit bloquée


UAI: Il reste l'overlap sur les fléches, c'est pas très joli.

2022-10-06 09:41 UTC, Teiwin commented
> > > ![image](https://user-images.githubusercontent.com/25371937/193948421-056163f7-7562-46e4-ae6f-8072417049ae.png) La PGCard dans l'historique c'est vraiment une super idée !
> > > Par contre ce serait cool que la fam'ss soit en justifié (genre de l'autre coté de la card) facile à faire avec Group en plus.
> > 
> > 
> > je n'ai pas d'idée de comment faire, les test que j'ai fait ne sont pas concluants... TODO?
> 
> ![image](https://user-images.githubusercontent.com/25371937/194171089-4c05934f-2fd3-40ad-8d8f-08ede455887a.png) Done ![image](https://user-images.githubusercontent.com/25371937/194171127-15bf6751-7565-45f2-9294-e1d7ac993a23.png)
> 
> Utilise vraiment un max les mises en page avec les styles (bon la avec les components et props comme on utilise mantine) c'est plutôt comme ça qu'il faut faire en web ( en plus comme ça le composant devient comme par magie quasi responsive)

Il reste un pb avec les grandes bucques sqrt(WentchououkououmiT'couilles) 
![image](https://user-images.githubusercontent.com/107307293/194280711-17cb212a-1554-4952-ba65-fa43869682c4.png)

2022-10-06 09:43 UTC, Teiwin commented on src/components/PgCard.jsx
> +export default function PgCard({data, small, onClick, style}) {
ça va faire bcp de code repetition....

2022-10-08 22:58 UTC, OSiG43 commented on src/components/NavigationBar.js
> +    const theme = useMantineTheme()
Je capte pas les changements que tu as fait dans ce fichier

2022-10-08 22:58 UTC, OSiG43 commented on src/components/PgCard.jsx
> +export default function PgCard({data, small, onClick, style}) {
Parce que c'est pas la peine des les changer de fichier, pour coup c'est pas choquant si dans PgCards.jsx il y a NormalCard et SmallCard.
Et du coup t'as pas à avoir 2 fichiers avec quasi les mêmes lignes, juste tu rends les composants accessible séparément

Après c'est un peu du détail en vrai

2022-10-08 22:58 UTC, OSiG43 commented on src/components/PgHistory.js
>  import {Table} from "@mantine/core";
Pas trop la peine de séparer les deux fichiers History je pense. Juste les composants

2022-10-09 10:11 UTC, OSiG43 requested changes
Le responsive est vraiment pas mal, j'ai quand même repéré quelques problèmes:

HomePage:
![image](https://user-images.githubusercontent.com/25371937/194750691-aa361326-cf33-4e52-ba4b-458ee4c1751b.png)

Problème sur d'affichage sur mobile, l'affichage est à cheval entre les deux tabs duc'ss ça fait un drole d'effet.


La Page PG est toujours dégueu par contre mais je suppose qu'elle n'est pas concernée par ta PR (Background bizare, PB de selection sur le tableau (on peut sélectionner des lignes qui duc'ss change de couleur)

2022-10-09 10:15 UTC, Teiwin commented on src/components/NavigationBar.js
> +    const theme = useMantineTheme()
j'ai rien changé :D
ce fichier c'est tout toi :laughing:

2022-10-09 10:16 UTC, Teiwin commented
> Le responsive est vraiment pas mal, j'ai quand même repéré quelques problèmes:
> 
> HomePage: ![image](https://user-images.githubusercontent.com/25371937/194750691-aa361326-cf33-4e52-ba4b-458ee4c1751b.png)
> 
> Problème sur d'affichage sur mobile, l'affichage est à cheval entre les deux tabs duc'ss ça fait un drole d'effet.
> 
> La Page PG est toujours dégueu par contre mais je suppose qu'elle n'est pas concernée par ta PR (Background bizare, PB de selection sur le tableau (on peut sélectionner des lignes qui duc'ss change de couleur)

effectivement, la je ne fais que la homepage

2022-10-09 10:34 UTC, OSiG43 commented
![image](https://user-images.githubusercontent.com/25371937/194751949-86f2e0a8-97a8-4a5d-807b-aa24034373ce.png)
Penser à Centrer Bucque et Fam'ss dans la small PG Card aussi

2022-10-09 11:05 UTC, Teiwin commented on src/components/PgHistory.js
>  import {Table} from "@mantine/core";
done

2022-10-09 13:41 UTC, OSiG43 requested changes
![image](https://user-images.githubusercontent.com/25371937/194760166-535fa527-0cf6-47fb-a3db-89d20e72ed79.png)

![image](https://user-images.githubusercontent.com/25371937/194760172-37721e52-0637-45f7-b8cb-606101f19738.png)

Problème sur la PG Card

Sinon c'est top !

2022-10-09 13:55 UTC, OSiG43 approved these changes

2022-10-09 17:24 UTC, merged